#!/usr/bin/env node
/**
 * Compiles lib/skills/catalog/<name>/SKILL.md files into bundled TypeScript:
 *
 *   lib/skills/catalog.generated.ts    — skill metadata + body
 *   lib/skills/resources.generated.ts  — bundled L3 resource files for skills
 *                                        that ship them (css/js/md/fonts/images),
 *                                        used by read_skill_file + render_artifact.
 *
 * Both are gitignored and regenerated by `pnpm skills:build` (and automatically
 * on dev/build/test/typecheck), so they never drift from the SKILL.md sources.
 * We generate code rather than reading files at runtime so the catalog ships
 * inside the serverless bundle — no filesystem access on Vercel.
 */
import { readFileSync, readdirSync, writeFileSync, existsSync, statSync } from 'node:fs';
import { join, dirname, relative, extname, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse as parseYaml } from 'yaml';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SKILLS_DIR = join(__dirname, '..', 'lib', 'skills');
const CATALOG_DIR = join(SKILLS_DIR, 'catalog');
const CATALOG_OUT = join(SKILLS_DIR, 'catalog.generated.ts');
const RESOURCES_OUT = join(SKILLS_DIR, 'resources.generated.ts');

const FRONTMATTER_RE = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/;

// Files/dirs inside a skill that are NOT runtime resources. The skill's own
// CLI scripts assume a shell + node; ekko renders in-process instead.
const SKIP_DIRS = new Set(['scripts']);
const SKIP_FILES = new Set(['SKILL.md']);

const TEXT_EXT = new Set(['.md', '.css', '.js', '.mjs', '.html', '.htm', '.svg', '.txt', '.json', '.csv']);
const MIME = {
  '.md': 'text/markdown',
  '.css': 'text/css',
  '.js': 'text/javascript',
  '.mjs': 'text/javascript',
  '.html': 'text/html',
  '.htm': 'text/html',
  '.svg': 'image/svg+xml',
  '.txt': 'text/plain',
  '.json': 'application/json',
  '.csv': 'text/csv',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.ttf': 'font/ttf',
  '.otf': 'font/otf',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif': 'image/gif',
  '.webp': 'image/webp',
  '.ico': 'image/x-icon',
  '.pdf': 'application/pdf',
};

function parseSkill(raw, name) {
  const match = FRONTMATTER_RE.exec(raw.trimStart());
  if (!match) throw new Error(`${name}: SKILL.md must start with YAML frontmatter`);
  const [, fm, body] = match;
  const data = parseYaml(fm ?? '') ?? {};
  if (!data.name || !/^[a-z0-9-]+$/.test(data.name)) throw new Error(`${name}: invalid 'name'`);
  if (!data.description) throw new Error(`${name}: missing 'description'`);
  const trimmed = (body ?? '').trim();
  if (!trimmed) throw new Error(`${name}: empty body`);
  return {
    name: data.name,
    description: data.description,
    body: trimmed,
    trigger: data.trigger ?? 'model',
    keywords: (data.keywords ?? []).map((k) => String(k).toLowerCase()),
    requiredTools: data.required_tools ?? [],
  };
}

/** Recursively collect resource files for one skill into a { relPath: entry } map. */
function collectResources(skillDir) {
  const out = {};
  const walk = (dir) => {
    for (const entry of readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
      const abs = join(dir, entry.name);
      const rel = relative(skillDir, abs).split(sep).join('/');
      if (entry.isDirectory()) {
        if (SKIP_DIRS.has(rel)) continue;
        walk(abs);
        continue;
      }
      if (SKIP_FILES.has(rel)) continue;
      const ext = extname(entry.name).toLowerCase();
      const mime = MIME[ext] || 'application/octet-stream';
      if (TEXT_EXT.has(ext)) {
        out[rel] = { mime, text: readFileSync(abs, 'utf8') };
      } else {
        out[rel] = { mime, base64: readFileSync(abs).toString('base64') };
      }
    }
  };
  walk(skillDir);
  return out;
}

const skills = [];
const resources = {};
if (existsSync(CATALOG_DIR)) {
  for (const entry of readdirSync(CATALOG_DIR, { withFileTypes: true }).sort((a, b) =>
    a.name.localeCompare(b.name),
  )) {
    if (!entry.isDirectory()) continue;
    const skillDir = join(CATALOG_DIR, entry.name);
    const file = join(skillDir, 'SKILL.md');
    if (!existsSync(file)) continue;
    const skill = parseSkill(readFileSync(file, 'utf8'), entry.name);
    if (skill.name !== entry.name) {
      throw new Error(`${entry.name}: frontmatter name "${skill.name}" must match directory name`);
    }
    const res = collectResources(skillDir);
    if (Object.keys(res).length) resources[skill.name] = res;
    skills.push({ ...skill, hasResources: Object.keys(res).length > 0 });
  }
}

const banner = (extra) =>
  '// AUTO-GENERATED by scripts/build-skills.mjs — do not edit.\n' +
  '// Edit the SKILL.md files in lib/skills/catalog/ and run `pnpm skills:build`.\n' +
  (extra ? extra : '');

writeFileSync(
  CATALOG_OUT,
  `${banner()}import type { Skill } from './types';\n\nexport const skills: Skill[] = ${JSON.stringify(
    skills,
    null,
    2,
  )};\n`,
);

writeFileSync(
  RESOURCES_OUT,
  `${banner()}import type { SkillResources } from './resources';\n\nexport const resources: SkillResources = ${JSON.stringify(
    resources,
    null,
    2,
  )};\n`,
);

const totalBytes = statSync(RESOURCES_OUT).size;
console.log(
  `Compiled ${skills.length} skill(s) → catalog.generated.ts; ` +
    `${Object.keys(resources).length} with resources → resources.generated.ts (${(totalBytes / 1024).toFixed(0)} KB)`,
);
