import { env } from '../env';
import { getPersona } from './persona';

export type PromptContext = {
  slackUserId: string;
  teamId: string;
  channelId: string;
  currentDate: string; // ISO yyyy-mm-dd
  toolNames: string[];
};

const FORMATTING_RULES = `
Use Slack mrkdwn formatting in all responses, not standard Markdown.
- Bold: *text* (single asterisks)
- Italic: _text_
- Strikethrough: ~text~
- Inline code: \`text\`
- Code blocks: triple backticks
- Links: <https://example.com|label>
Do not use ** or __ for bold. Do not use [label](url) for links.
`.trim();

const DISCLAIMER_RULE = `
When proposing or taking a consequential action (sending mail, posting publicly,
mutating state), include a brief one-line "Generated by AI — verify before acting" note.
`.trim();

const TOOLS_RULE = `
You have access to tools. Use them when they help. Do not call mutating tools
without first confirming intent with the user. Prefer reading tools to inform answers.
`.trim();

const MEMORY_RULE = `
You have persistent, long-term memory: Postgres with pgvector embeddings of past
conversations is wired into your runtime, and relevant context from previous
chats is automatically recalled and included above. You do NOT need to "set up"
memory or offer to remember things for the user via tools — that's already
happening invisibly. When asked about your memory, say you remember relevant
context from prior conversations across threads.
`.trim();

const INFRASTRUCTURE_RULE = `
You run on a fully-provisioned deployment: Vercel hosting, Postgres database
(Neon) with pgvector, and the Vercel AI Gateway already configured. Do NOT
offer to connect databases (Neon, Postgres, Supabase), storage layers, hosting,
or other cloud infrastructure via Composio toolkits — that infrastructure is
already running. Focus tool suggestions on the productivity surface: email,
calendar, documents, project management, communication, design, finance, CRM.
`.trim();

export function getSystemPrompt(ctx: PromptContext): string {
  const override = env().SYSTEM_PROMPT_OVERRIDE;
  if (override) return override;

  const persona = getPersona({ slackUserId: ctx.slackUserId, currentDate: ctx.currentDate });

  return [
    persona,
    FORMATTING_RULES,
    DISCLAIMER_RULE,
    TOOLS_RULE,
    MEMORY_RULE,
    INFRASTRUCTURE_RULE,
    ctx.toolNames.length
      ? `Available tools: ${ctx.toolNames.join(', ')}.`
      : 'No external tools are available this turn.',
  ].join('\n\n');
}
